const suplementosNaturales = {
  suplementos: [
    {
      id: 1,
      image: "magnesio con potasio.png",
      name: "Multi Magnesio con Potasio - 30 Cápsulas Vitamin Way",
      description:
        "MAGNESIO con Potasio y Vitamina B6 – 450 mg. Ayuda a prevenir la aparición de calambres. Favorece el buen funcionamiento muscular. Contribuye al equilibrio electrolítico. Favorece la producción de energía celular. Combinación de tres clases de magnesio para optimizar su biodisponibilidad.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas",
      ingesta: "1 cápsula diaria.",
      marca: "PHARMAMERICAN",
      price: 1314,
    },
    {
      id: 2,
      image: "colageno-calcio.png",
      name: "COLÁGENO + CALCIO X30 CÁPSULAS VITAMIN WAY",
      description:
        "Colágeno + Calcio Vitamin Way® ayuda a aumentar la elasticidad de la piel y aporta los nutrientes necesarios para mantenerla saludable. Su fórmula ayuda a fortalecer cabello, piel y uñas y aporta antioxidantes que protegen la piel de la radiación UV.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas",
      ingesta: "1 cápsula diaria.",
      marca: "PHARMAMERICAN",
      price: 1820,
    },
    {
      id: 3,
      image: "detox.png",
      name: "DETOX CON ÁCIDO ALFALIPOICO Y CURCUMA X30 CÁPSULAS VITAMIN WAY",
      description:
        "El suplemento nutricional Detox Vitamin Way® ayuda al organismo a eliminar lo que no necesita. Sus ingredientes ayudan a optimizar el funcionamiento de los órganos encargados de la eliminación de toxinas.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas",
      ingesta: "1 cápsula diaria.",
      marca: "PHARMAMERICAN",
      price: 2550,
    },
    {
      id: 4,
      image: "cabello-piel-y-unas.png",
      name: "CABELLO, PIEL Y UÑAS X30 CÁPSULAS VITAMIN WAY",
      description:
        "El suplemento nutricional Cabello, Piel y Uñas Vitamin Way® ayuda a fortalecer y embellecer cabello, piel y uñas. Esta fórmula aporta los nutrientes necesarios para lucir el cabello sano y resistente a las agresiones del medio ambiente, la piel tersa y luminosa y las uñas hidratadas y menos frágiles.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas",
      ingesta: "1 cápsula diaria.",
      marca: "PHARMAMERICAN",
      price: 2550,
    },
    {
      id: 5,
      image: "vitamina-c.png",
      name: "VITAMINA C CON ZINC X30 CÁPSULAS VITAMIN WAY",
      description:
        "El suplemento nutricional Vitamina C Vitamin Way® ayuda a fortalecer las defensas del organismo. La ingesta conjunta de vitamina C y zinc mejora los síntomas y disminuye la duración de infecciones respiratorias, incluyendo el resfrío. La vitamina C favorece la absorción intestinal del hierro y es un importante antioxidante.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas",
      ingesta: "1 cápsula diaria.",
      marca: "PHARMAMERICAN",
      price: 1620,
    },
    {
      id: 6,
      image: "MAGNESIO 50 CAP NATIER.jpg",
      name: "MAGNESIO 50 CAP - NATIER",
      description:
        "Ayuda a la relajación y contracción muscular Fórmula de mayor biodisponibilidad y absorción. Estimula la creación de hueso Ayuda a regular el stress, ansiedad e insomnio El magnesio participa en 300 reacciones bioquímicas, como la formación y remineralización de hueso, el buen estado de la pared de las arterias y el control glucémico..",
      category: "Suplemento Natural",
      cantidad: "50 cápsulas",
      ingesta: "4 cápsulas diarias.",
      marca: "Nathier",
      price: 3390,
    },
    {
      id: 7,
      image: "vitamina-c-concentrada.jpg",
      name: "VITAMINA C CONCENTRADA 50 CAP – NATIER",
      description:
        "Nuestra fórmula extraída de fuentes naturales es altamente efectiva y biodisponible. Puede ser ingerida en cualquier momento del día o bien 30 minutos antes o después de cualquiera de las principales comidas, para su correcta y total absorción.",
      category: "Suplemento Natural",
      cantidad: "50 cápsulas",
      ingesta: "4 cápsulas diarias.",
      marca: "Nathier",
      price: 3120,
    },
    {
      id: 8,
      image: "Hydro-farming-Spirulina-con-Garcinia-REDUCTORA.jpg",
      name: "SPIRULINA REDUCTORA CON GARCINIA 60 CAPSULAS – BOGADO",
      description:
        "Incorporando Spirulina reductora con garcinia ayudás a tu cuerpo a ponerse en forma, acompañando con un régimen alimentario saludable y una rutina de ejercicios.",
      category: "Suplemento Natural",
      cantidad: "60 comprimidos",
      ingesta: "4 comprimidos diarios.",
      marca: "Bogado",
      price: 2650,
    },
    {
      id: 9,
      image: "vitamina-b12.jpg",
      name: "VITAMINA B12 50 CAP – NATIER",
      description:
        "La Vitamina B12 es una vitamina esencial que nuestro organismo no tiene la capacidad de producir y que está presente casi exclusivamente en los alimentos de origen animal. Por esto las dietas veganas y vegetarianas pueden ser deficitarias en esta vitamina produciendo anemias crónicas.",
      category: "Suplemento Natural",
      cantidad: "50 cápsulas",
      ingesta: "4 cápsulas diarias.",
      marca: "Nathier",
      price: 3980,
    },
    {
      id: 10,
      image: "SPIRULINA-CON-CLOROFILA.jpg",
      name: "SPIRULINA CON CLOROFILA 30 CAPSULAS – BOGADO",
      description:
        "En cápsulas vegetales, te ayudarán a consumir CLOROFILA de manera rápida efectiva y sin conservantes. La spirulina constituye uno de los primeros microorganismos del planeta. Es un alga microscópica azul-verde que crece en aguas dulces y pertenece a la familia de las llamadas cianobacterias.",
      category: "Suplemento Natural",
      cantidad: "30 cápsulas vegetales",
      ingesta: "4 cápsulas diarias.",
      marca: "Bogado",
      price: 2220,
      
    }
    
  ],
},
const alimentosOrganicos = {
  suplementos: [
    {
      id: 11,
      image: "",
      name: "Mix de Frutos Secos Premium",
      description:
        "Los frutos secos son un elemento fundamental dentro de la Dieta Mediterránea. Destacan por su alto contenido energético, así como por su aporte de proteínas, fibra, minerales y vitaminas como la vitamina E. Armalo a tu gusto, con frutos secos de primera calidad: Almendras, Nueces, Castañas de Caju, Mani, Pasas Negras y Pasas Rubias. Arma tu Mix a tu gusto",
      category: "Alimento Organico",
      cantidad: "250 gr",
      ingesta: "20 a 30 gramos por dia",
      marca: "Artesanal",
      price: 1250,
    },
    {
      id: 12,
      image: "",
      name: "Frutas deshidratadas",
      description:
        "El contenido en nutrientes de las Frutas deshidratas es similar al de la fruta fresca, aunque con un contenido más concentrado de azúcar, vitaminas y  minerales. Arma tu Mix a tu gusto: arándanos,piña, kiwi, manzana, coco o mango",
      category: "Alimento Organico",
      cantidad: "250 gr",
      ingesta: "1 racion diaria",
      marca: "Artesanal",
      price: 1220,
    },
    {
      id: 13,
      image: "",
      name: "Granola",
      description:
        "Mezcla de nueces, copos de avena mezclados con miel y otros ingredientes naturales. Especial para todos tus desayunos y meriendas ",
      category: "Alimento Organico",
      cantidad: "300 gr",
      ingesta: "100 gramos al dia",
      marca: "Artesanal",
      price: 850,
    },
    {
      id: 14,
      image: "",
      name: "Avena en Hojuelas",
      description:
        "Rica en proteínas y antioxidantes, la avena aporta numerosos nutrientes a nuestro organismo. Rica en proteínas y antioxidantes, la avena aporta numerosos nutrientes a nuestro organismo y ayuda en la perdida de peso",
      category: "Alimento Organico",
      cantidad: "1 kg",
      ingesta: "25 a 30 gramos al dia",
      marca: "Artesanal",
      price: 870,
    },
    {
      id: 15,
      image: "",
      name: "Cereales",
      description:
        "Los cereales integrales aportan fibra, vitaminas, minerales y otros nutrientes. Elegi el sabor que mas te guste: maiz natural, maiz sabor a chocolate, frutas",
      category: "Alimentos Organicos",
      cantidad: "500 gr",
      ingesta: "1/4 tazon al dia",
      marca: "Artesanal",
      price: 790,
    },
    {
      id: 16,
      image: "",
      name: "Mermeladas sin azucar",
      description:
        "La mermelada artesanal te aporta energía, grasas y glucosa. Esto beneficia especialmente a las personas muy activas: deportistas, niños... ¡Los azúcares naturales deben estar presentes en nuestra dieta, y las mermeladas artesanales sin azúcar común son el complemento perfecto! Elegi tu sabor favorito: Frutilla, Frutos Rojos, Ciruela o Naranja",
      category: "Alimentos Organicos",
      cantidad: "390 gr",
      ingesta: "2 cucharadas al dia",
      marca: "Artesanal",
      price: 2300,
    },
    {
      id: 17,
      image: "",
      name: "Pasta de Mani",
      description:
        "Pasta elaborada con maníes secos, tostados y molidos. Una porción de mantequilla de maní te dará 3 mg de vitamina E, la cual es antioxidante. También obtienes 49 gramos de magnesio, que ayuda a los huesos y la recuperación de los músculosPasta elaborada con maníes secos, tostados y molidos. Una porción de mantequilla de maní te dará 3 mg de vitamina E, la cual es antioxidante. También obtienes 49 gramos de magnesio, que ayuda a los huesos y la recuperación de los músculos.",
      category: "Alimento Organico",
      cantidad: "510 gr",
      ingesta: "2 cucharadas al dia",
      marca: "Artesanal",
      price: 1200,
    },
    {
      id: 18,
      image: "",
      name: "Galletas de Arroz",
      description:
        "Crocantes galletitas elaboradas con arroz integral. Ideales para untar, acompañar una comida o como snack. Disfruta de tus comidas de una manera natural, sin conservantes ni aditivos, y sin gluten.",
      category: "Alimentos Organicos",
      cantidad: "150 gr",
      ingesta: "2 galletas diarias",
      marca: "Artesanal",
      price: 350,
    },
    {
      id: 19,
      image: "",
      name: "Pack de Regalo Frutos Secos",
      description:
        "Especialmente armado para regalo, pack de frutos secos, frutas deshidratas, manies bañados en chocolate",
      category: "Alimentos Organicos",
      cantidad: "300 gr",
      ingesta: "1 porcion dia",
      marca: "Artesanal",
      price: 2350,
    },
    {
      id: 20,
      image: "",
      name: "Galletitas Integrales",
      description:
        "Línea de galletitas dulces sin azucar añadido",
      category: "Alimentos Organicos",
      cantidad: "200 gr",
      ingesta: "1 porcion dia",
      marca: "Artesanal",
      price: 600,
    },
  ]}